### ISSUE TITLE
"From Version" and "To Version" in Logs

### ISSUE THREAD

**Issue by mpsparrow** [easy-updates-manager/easy-updates-manager#193]
https://wordpress.org/support/topic/feature-request-both-from-version-and-to-version-in-the-update-logs/

If you think about it only one more column would need to be added in order to do this.

**Comment by ronalfy** [comment]
Can you foresee any others?

**Comment by ronalfy** [comment]
@mpsparrow in the dev branch, there is logic to allow for this. 

I've done my fair share of testing, but if you can help, that would be appreciated.

The way I'm getting the version numbers is a bit whacky as I have to store my own version of plugin/theme assets in a temporary transient.

Translations have no "from" version, so I default to just adding the current version.

**Comment by mpsparrow** [comment]
@ronalfy Just noticed this now. Will test it in the morning.

**Comment by mpsparrow** [comment]
Hmm..... so I updated some themes as a test. The version to works great. Version from is the current version as you said. Strangely enough it showed that both the updates failed although the obviously didn't. Let me do a little more testing and see.

**Comment by ronalfy** [comment]
@mpsparrow this may be due to the update transient.

How are you testing?  I installed a plugin called <a href="https://wordpress.org/plugins/artiss-transient-cleaner/">Transient Cleaner</a> to clean out any transients.

The `develop` branch stores a copy of the plugins/themes in a 30 minute transient that way there is a way to compare the previous and updated version.

For my testing, for example, I'd edit a plugin's/theme's heading to be a previous version, clear the transients, then run a manual or automatic update.

This assumes quite a bit, but is the only way I've been able to get the `from` version to work. The assumption being, that 30 minutes is plenty of time for casual WordPress users and will only affect the testing of logs by us since we're going to be changing things a lot during a 30 minute period.

I hope that makes sense.

**Comment by mpsparrow** [comment]
@ronalfy makes sense. I will try that and see what the outcome is.

**Comment by mpsparrow** [comment]
@ronalfy Just tested that and it works flawlessly once I clear the transient.

**Comment by ronalfy** [comment]
Cool. I also added transient cleaning when you click Force Updates in the
most recent commit. That should shave some testing down. No work around for
manual updates though.

**Comment by ronalfy** [comment]
@mpsparrow I'm about ready to deploy this. I feel like I'm playing bug whack-a-mole, and the current status is no bugs, so I'll delay until tomorrow sometime and do some sanity testing on the logs.

**Comment by mpsparrow** [comment]
@ronalfy I agree. Go ahead whenever you are ready to release it.

**Comment by ronalfy** [comment]
I'm happy with my current tests :)

![screen shot 2017-11-07 at 11 52 26 am](https://user-images.githubusercontent.com/636521/32509185-368c674e-c3b2-11e7-8555-2ed7b7094b41.png)
