### ISSUE TITLE
Style Suggestions for new Admin UI

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#203]
![screencapture-localhost-osu-wp-admin-index-php-1515704259241](https://user-images.githubusercontent.com/636521/34847035-a9fb1616-f6df-11e7-86e4-b28f28f869fc.png)

Here's the new admin UI. Any suggestions are appreciated.

**Comment by roarytubbs** [comment]
@ronalfy 
Looks good, only recommendation I have is around your toggles. Reading isn't 100% clear. I'd recommend changing the labels to say either "enabled" or "disabled" based on it's status.  For example instead of saying **Enable or Disable All Updates**, if it's enabled, say "All Updates are Enabled". Offer up a bit more clarity.

**Comment by ronalfy** [comment]
Hey @roarytubbs I redid the entire admin based on your and Paal's recommendations.

Here's a download link: https://github.com/easy-updates-manager/easy-updates-manager/archive/dev.zip
