### ISSUE TITLE
Notification E-mails

### ISSUE THREAD

**Issue by ronalfy** [easy-updates-manager/easy-updates-manager#44]
A user requested a feature be added to the plugin to manage e-mail notifications.

https://wordpress.org/support/topic/change-address-email-that-receive-update-report

I can see why a user would want this part of the plugin, just want to know if it makes sense to add it in, and if so, where to add it in.

If we do add it in, I fear it will be an additional support burden when people start having e-mail issues.

**Comment by mpsparrow** [comment]
I don't think this is worth a new setting. You said it best:

> If we do add it in, I fear it will be an additional support burden when people start having e-mail issues.

Although I do think that we should add some sort of documentation staying how to change it just so that we don't get a million support questions. I will add an FAQ to the readme.txt along with adding a FAQ to the wiki. I will basically say exactly what you replied in the topic.

> There's some documentation about changing the notification e-mail here: http://www.iwebcontrol.co.uk/2013/10/change-wordpress-auto-update-email-address/
> 
> A plugin was also created to change the background updates email address: https://wordpress.org/plugins/background-update-notification-email-address/ 

I will mark this as closed once I add the FAQ's.

**Comment by mpsparrow** [comment]
To do:
- [x] Add readme.txt FAQ
- [x] Add a wiki FAQ

**Comment by mpsparrow** [comment]
If you what to add anything to the FAQ go ahead.

**Comment by ronalfy** [comment]
Thanks.  Looks good.
